openapi: 3.0.3
info:
  description: Simple API for performance testing
  title: Api performance testing
  version: 1.1.0
servers:
- url: /
paths:
  /hello:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: successful operation
      summary: Returns simple JSON object with "Hello World!" text
  /fibonacci/{n}:
    get:
      parameters:
      - description: number of Fibonacci element to return
        explode: false
        in: path
        name: "n"
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fibonacci'
          description: successful operation
      summary: Returns n-th element of Fibonacci Sequence in a JSON object
  /database:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: successful operation
      summary: Returns random element from database
components:
  schemas:
    Message:
      example:
        message: message
      properties:
        message:
          title: message
          type: string
      title: Message
      type: object
    Fibonacci:
      example:
        number: 0
        value: 6
      properties:
        number:
          title: number
          type: integer
        value:
          title: value
          type: integer
      title: Fibonacci
      type: object
