# coding: utf-8

"""
    Api performance testing

    Simple API for performance testing

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Api performance testing",
    description="Simple API for performance testing",
    version="1.1.0",
)

app.include_router(DefaultApiRouter)
