services:
  mariadb:
    image: mariadb:11.5.1-rc
    container_name: "mariadb"
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  fastapi:
    image: "fastapi"
    container_name: "fastapi"
    build: fastapi/
    restart: unless-stopped
    ports:
      - "8080:8080"

  spring:
    image: "spring"
    container_name: "spring"
    build: spring/
    restart: unless-stopped
    ports:
      - "8080:8080"
      
  gin:
    image: "gin"
    container_name: "gin"
    build: gin/
    restart: unless-stopped
    ports:
      - "8080:8080"