openapi: 3.0.3
info:
  description: Simple API for performance testing
  title: Api performance testing
  version: 1.0.0
servers:
- url: /
paths:
  /hello:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: successful operation
      summary: Returns simple text
      x-accepts:
      - application/json
components:
  schemas:
    Response:
      example:
        data: data
      properties:
        data:
          type: string
      type: object
