version: '3.1'

services:
  mariadb:
    image: "mariadb"
    container_name: "mariadb"
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
